version: '3.8'

services:
  remarkable-update:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: remarkable-update-server
    ports:
      - "8000:8000"
    volumes:
      # Mount NFS updates directory to container
      - remarkable_updates:/app/updates
      # Optional: mount logs for debugging
      - remarkable_logs:/app/logs
    environment:
      # Set this to your computer's IP address that the reMarkable can reach
      # For USB connection: usually 10.11.99.2 (device will connect on port 80)
      # For WiFi connection: your local IP (e.g., 192.168.1.25)
      - HOST_IP=192.168.0.154
    networks:
      - remarkable-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  remarkable-net:
    driver: bridge

volumes:
  remarkable_updates:
    driver_opts:
      type: nfs
      device: ":/Docker/remarkable-update/updates"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  remarkable_logs:
    driver_opts:
      type: nfs
      device: ":/Docker/remarkable-update/logs"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
